apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: transcendence
data:
  NODE_ENV: "production"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  ALLOWED_ORIGINS: "https://transcendence.local"
