apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: transcendence
data:
  NODE_ENV: "development"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  ALLOWED_ORIGINS: "https://transcendence.local"
  DB_SSL_ENABLED: "true"
  DB_SSL_REJECT_UNAUTHORIZED: "true"
  DB_SSL_CA_PATH: "/etc/postgres-ca/ca.crt"
