apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: transcendence
data:
  vault-config.hcl: |
    ui = false

    listener "tcp" {
      address = "[::]:8200"
      tls_disable = 0
      tls_cert_file = "/vault/tls/tls.crt"
      tls_key_file = "/vault/tls/tls.key"
      tls_min_version = "tls12"
      tls_client_ca_file = "/vault/tls/ca.crt"
      cluster_address = "[::]:8201"
    }

    storage "raft" {
      path = "/vault/data"
      node_id = "POD_NAME"
    }

    disable_mlock = true

    api_addr = "https://POD_NAME.vault-internal.transcendence.svc.cluster.local:8200"
    cluster_addr = "https://POD_NAME.vault-internal.transcendence.svc.cluster.local:8201"

    telemetry {
      disable_hostname = true
    }

    log_level = "info"
