apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: transcendence
spec:
  secretName: vault-tls
  duration: 8760h
  renewBefore: 720h
  privateKey:
    rotationPolicy: Always
  subject:
    organizations:
      - transcendence
  commonName: vault.transcendence.svc.cluster.local
  dnsNames:
    - vault
    - vault.transcendence.svc.cluster.local
    - "*.vault-internal.transcendence.svc.cluster.local"
    - vault-0.vault-internal
    - vault-1.vault-internal
    - vault-2.vault-internal
    - localhost
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: vault-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: transcendence
spec:
  selfSigned: {}
