apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: transcendence
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: transcendence
spec:
  secretName: vault-tls
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: vault-issuer
    kind: Issuer
  dnsNames:
    - vault
    - vault.transcendence.svc.cluster.local
    - vault-0.vault-internal.transcendence.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
